"""TestBench-Forge — an RL gym that trains agents to write the test suite that catches
the most bugs.

The agent is shown a module + its reference implementation and must write a pytest-style
test suite (functions named test_*). Reward = fraction of HIDDEN, freshly-injected mutants
(buggy variants of the reference) that the suite KILLS — gated by the suite passing on the
reference and on behavior-equivalent refactors (the over-specification penalty).

Non-gameable:
  - assert-False (or any suite that fails the reference) -> fails the gate -> reward 0.
  - mutants are never shown -> the agent can't target them; it must learn coverage strategy.
  - the over-spec gate kills brittle snapshot tests that depend on impl internals.

Mutants are generated by AST mutation operators (operator flips, off-by-one constants) plus
a few curated semantic bugs, then differentially filtered against the reference so the pool
contains only NON-equivalent (genuinely killable) mutants — giving a clean ceiling.
"""
from __future__ import annotations

import ast
import copy
import hashlib
import json
import random
import subprocess
import sys

# ---------------------------------------------------------------------------
# subprocess harnesses (untrusted code + our generated mutants run isolated)
# ---------------------------------------------------------------------------

_SUITE_RUNNER = r'''
import json, sys
d = json.loads(sys.stdin.read())
ns = {}
try:
    exec(d["impl"], ns)
except Exception:
    pass  # tests calling the (now-undefined) function will fail -> mutant killed
try:
    exec(d["suite"], ns)
except Exception:
    print(json.dumps({"passed": False, "n": 0})); raise SystemExit
tests = [v for k, v in list(ns.items()) if k.startswith("test_") and callable(v)]
if not tests:
    print(json.dumps({"passed": False, "n": 0})); raise SystemExit
for t in tests:
    try:
        t()
    except Exception:
        print(json.dumps({"passed": False, "n": len(tests)})); raise SystemExit
print(json.dumps({"passed": True, "n": len(tests)}))
'''

_EVAL_RUNNER = r'''
import json, sys
d = json.loads(sys.stdin.read())
ns = {}
try:
    exec(d["impl"], ns)
except Exception:
    print(json.dumps({"sig": ["IMPORT_ERR"] * len(d["inputs"])})); raise SystemExit
fn = ns.get(d["func"])
if not callable(fn):
    print(json.dumps({"sig": ["NO_FUNC"] * len(d["inputs"])})); raise SystemExit
sig = []
for args in d["inputs"]:
    try:
        v = fn(*args)
        try:
            sig.append("OK:" + json.dumps(v, sort_keys=True))
        except Exception:
            sig.append("OK:" + repr(v))
    except Exception as e:
        sig.append("ERR:" + type(e).__name__)
print(json.dumps({"sig": sig}))
'''


def _run_suite_once(impl_src: str, suite_src: str, timeout: float = 4.0) -> bool:
    """True iff the suite PASSES against this implementation."""
    payload = json.dumps({"impl": impl_src, "suite": suite_src})
    try:
        proc = subprocess.run([sys.executable, "-c", _SUITE_RUNNER], input=payload,
                              capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return False  # a hanging impl/test => not a pass (so a hanging mutant is killed)
    out = (proc.stdout or "").strip().splitlines()
    if not out:
        return False
    try:
        return bool(json.loads(out[-1]).get("passed"))
    except Exception:
        return False


def _eval_signature(impl_src: str, func: str, inputs: list, timeout: float = 4.0) -> list:
    payload = json.dumps({"impl": impl_src, "func": func, "inputs": inputs})
    try:
        proc = subprocess.run([sys.executable, "-c", _EVAL_RUNNER], input=payload,
                              capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return ["TIMEOUT"] * len(inputs)
    out = (proc.stdout or "").strip().splitlines()
    if not out:
        return ["EVAL_ERR"] * len(inputs)
    try:
        return json.loads(out[-1]).get("sig", ["EVAL_ERR"] * len(inputs))
    except Exception:
        return ["EVAL_ERR"] * len(inputs)


# ---------------------------------------------------------------------------
# AST mutation engine
# ---------------------------------------------------------------------------

_CMP_FLIPS = {
    ast.Lt: [ast.LtE, ast.Gt], ast.LtE: [ast.Lt, ast.GtE],
    ast.Gt: [ast.GtE, ast.Lt], ast.GtE: [ast.Gt, ast.LtE],
    ast.Eq: [ast.NotEq], ast.NotEq: [ast.Eq],
}
_BIN_FLIPS = {ast.Add: ast.Sub, ast.Sub: ast.Add, ast.Mult: ast.Add}
_BOOL_FLIPS = {ast.And: ast.Or, ast.Or: ast.And}


def _gen_ast_mutants(src: str) -> list:
    base = ast.parse(src)
    for i, n in enumerate(ast.walk(base)):
        n._mid = i
    targets = []  # (mid, kind, payload)
    for n in ast.walk(base):
        if isinstance(n, ast.Compare) and len(n.ops) == 1:
            for new in _CMP_FLIPS.get(type(n.ops[0]), []):
                targets.append((n._mid, "cmp", new))
        elif isinstance(n, ast.BinOp) and type(n.op) in _BIN_FLIPS:
            targets.append((n._mid, "bin", _BIN_FLIPS[type(n.op)]))
        elif isinstance(n, ast.BoolOp) and type(n.op) in _BOOL_FLIPS:
            targets.append((n._mid, "bool", _BOOL_FLIPS[type(n.op)]))
        elif isinstance(n, ast.Constant) and isinstance(n.value, int) and not isinstance(n.value, bool):
            targets.append((n._mid, "const", n.value + 1))
            targets.append((n._mid, "const", n.value - 1))
            if n.value not in (0, 1):
                targets.append((n._mid, "const", 0))

    out = []
    for mid, kind, payload in targets:
        t = copy.deepcopy(base)
        for n in ast.walk(t):
            if getattr(n, "_mid", None) == mid:
                if kind == "cmp":
                    n.ops = [payload()]
                elif kind in ("bin", "bool"):
                    n.op = payload()
                elif kind == "const":
                    n.value = payload
                break
        try:
            out.append(ast.unparse(ast.fix_missing_locations(t)))
        except Exception:
            pass
    return out


def _stable_seed(s: str) -> int:
    return int(hashlib.sha256(s.encode()).hexdigest(), 16) % (2**31)


# ---------------------------------------------------------------------------
# modules under test
# ---------------------------------------------------------------------------

MERGE_REF = '''def merge_intervals(intervals):
    if not intervals:
        return []
    s = sorted(intervals)
    out = [[s[0][0], s[0][1]]]
    for a, b in s[1:]:
        if a <= out[-1][1]:
            out[-1][1] = max(out[-1][1], b)
        else:
            out.append([a, b])
    return out
'''
MERGE_EQUIV = '''def merge_intervals(intervals):
    res = []
    for iv in sorted(intervals):
        if res and iv[0] <= res[-1][1]:
            res[-1][1] = max(res[-1][1], iv[1])
        else:
            res.append([iv[0], iv[1]])
    return res
'''
MERGE_BUGS = [
    "def merge_intervals(intervals):\n    return [list(x) for x in sorted(intervals)]\n",  # never merges
    "def merge_intervals(intervals):\n    return [list(x) for x in intervals]\n",            # no sort, no merge
]

BAL_REF = '''def is_balanced(s):
    pairs = {')': '(', ']': '[', '}': '{'}
    st = []
    for c in s:
        if c in '([{':
            st.append(c)
        elif c in ')]}':
            if not st or st.pop() != pairs[c]:
                return False
    return not st
'''
BAL_EQUIV = '''def is_balanced(s):
    open_for = {')': '(', ']': '[', '}': '{'}
    stack = []
    for ch in s:
        if ch in '([{':
            stack.append(ch)
        elif ch in ')]}':
            if len(stack) == 0:
                return False
            if stack[-1] != open_for[ch]:
                return False
            stack.pop()
    return len(stack) == 0
'''
BAL_BUGS = [
    # ignores bracket TYPE: any closer matches any opener
    "def is_balanced(s):\n    st = []\n    for c in s:\n        if c in '([{':\n            st.append(c)\n        elif c in ')]}':\n            if not st:\n                return False\n            st.pop()\n    return not st\n",
    # ignores trailing unmatched openers
    "def is_balanced(s):\n    pairs = {')': '(', ']': '[', '}': '{'}\n    st = []\n    for c in s:\n        if c in '([{':\n            st.append(c)\n        elif c in ')]}':\n            if not st or st.pop() != pairs[c]:\n                return False\n    return True\n",
]

TWO_REF = '''def two_sum(nums, target):
    seen = {}
    for i, x in enumerate(nums):
        if target - x in seen:
            return [seen[target - x], i]
        seen[x] = i
    return None
'''
TWO_EQUIV = '''def two_sum(nums, target):
    pos = {}
    for idx in range(len(nums)):
        need = target - nums[idx]
        if need in pos:
            return [pos[need], idx]
        pos[nums[idx]] = idx
    return None
'''
TWO_BUGS = [
    # returns the VALUES instead of the indices
    "def two_sum(nums, target):\n    seen = set()\n    for x in nums:\n        if target - x in seen:\n            return [target - x, x]\n        seen.add(x)\n    return None\n",
    # allows using the same index twice
    "def two_sum(nums, target):\n    for i in range(len(nums)):\n        for j in range(len(nums)):\n            if nums[i] + nums[j] == target:\n                return [i, j]\n    return None\n",
]

RLE_REF = '''def run_length_encode(s):
    if not s:
        return ''
    out = []
    prev = s[0]
    cnt = 1
    for c in s[1:]:
        if c == prev:
            cnt += 1
        else:
            out.append(prev + str(cnt))
            prev = c
            cnt = 1
    out.append(prev + str(cnt))
    return ''.join(out)
'''
RLE_EQUIV = '''def run_length_encode(s):
    import itertools
    return ''.join(ch + str(len(list(g))) for ch, g in itertools.groupby(s))
'''
RLE_BUGS = [
    # omits the count for the final run
    "def run_length_encode(s):\n    if not s:\n        return ''\n    out = []\n    prev = s[0]\n    cnt = 1\n    for c in s[1:]:\n        if c == prev:\n            cnt += 1\n        else:\n            out.append(prev + str(cnt))\n            prev = c\n            cnt = 1\n    out.append(prev)\n    return ''.join(out)\n",
]


def _gen_intervals(rng):
    k = rng.randint(0, 5)
    return ([[(a := rng.randint(0, 10)), a + rng.randint(0, 5)] for _ in range(k)],)

def _gen_brackets(rng):
    return ("".join(rng.choice("()[]{}") for _ in range(rng.randint(0, 8))),)

def _gen_twosum(rng):
    nums = [rng.randint(0, 9) for _ in range(rng.randint(2, 6))]
    return (nums, rng.randint(0, 18))

def _gen_rle(rng):
    return ("".join(rng.choice("abc") for _ in range(rng.randint(0, 8))),)


MODULES = {
    "merge_intervals": {
        "func": "merge_intervals",
        "description": "Merge a list of [start, end] intervals; return the merged intervals sorted by start. Touching intervals (e.g. [1,2] and [2,3]) merge.",
        "reference": MERGE_REF, "equivalents": [MERGE_EQUIV], "extra_mutants": MERGE_BUGS,
        "gen": _gen_intervals,
        "edges": [([],), ([[1, 4]],), ([[1, 2], [2, 3]],), ([[1, 10], [2, 3]],), ([[8, 10], [1, 3], [2, 6]],)],
    },
    "is_balanced": {
        "func": "is_balanced",
        "description": "Return True iff the brackets in the string are balanced and correctly nested for (), [], {}.",
        "reference": BAL_REF, "equivalents": [BAL_EQUIV], "extra_mutants": BAL_BUGS,
        "gen": _gen_brackets,
        "edges": [("",), ("()",), ("(]",), ("([)]",), ("(((",), ("([{}])",)],
    },
    "two_sum": {
        "func": "two_sum",
        "description": "Return the indices [i, j] (i != j) of the two numbers that sum to target, or None. Return the FIRST such pair found scanning left to right.",
        "reference": TWO_REF, "equivalents": [TWO_EQUIV], "extra_mutants": TWO_BUGS,
        "gen": _gen_twosum,
        "edges": [([3, 3], 6), ([1, 2, 3], 7), ([0, 4, 3, 0], 0), ([2, 7, 11, 15], 9)],
    },
    "run_length_encode": {
        "func": "run_length_encode",
        "description": "Run-length encode a string: 'aaab' -> 'a3b1'. Every run, including singletons, gets a count.",
        "reference": RLE_REF, "equivalents": [RLE_EQUIV], "extra_mutants": RLE_BUGS,
        "gen": _gen_rle,
        "edges": [("",), ("a",), ("aaab",), ("abc",), ("aabbbc",)],
    },
}

_POOL_CACHE: dict[str, list] = {}
MAX_MUTANTS = 18


def _filter_inputs(module_id: str):
    m = MODULES[module_id]
    rng = random.Random(_stable_seed("inputs:" + module_id))
    inputs = list(m["edges"]) + [m["gen"](rng) for _ in range(30)]
    # normalize tuples -> lists for JSON round-trip (args are passed as a list)
    return [list(args) for args in inputs]


def get_mutant_pool(module_id: str) -> list:
    """Non-equivalent, killable mutants of the reference (cached, deterministic)."""
    if module_id in _POOL_CACHE:
        return _POOL_CACHE[module_id]
    m = MODULES[module_id]
    func = m["func"]
    inputs = _filter_inputs(module_id)
    ref_sig = _eval_signature(m["reference"], func, inputs)

    candidates = _gen_ast_mutants(m["reference"]) + list(m["extra_mutants"])
    seen, pool = set(), []
    for src in candidates:
        if src == m["reference"] or src in seen:
            continue
        seen.add(src)
        if _eval_signature(src, func, inputs) != ref_sig:   # non-equivalent => killable
            pool.append(src)
        if len(pool) >= MAX_MUTANTS:
            break
    _POOL_CACHE[module_id] = pool
    return pool


def score_suite(module_id: str, suite_src: str):
    """Reward = (#mutants killed / #mutants) gated by passing reference + equivalents."""
    m = MODULES[module_id]
    gate_impls = [m["reference"]] + m["equivalents"]
    for impl in gate_impls:
        if not _run_suite_once(impl, suite_src):
            return 0.0, {"gate": False, "reason": "suite fails reference or an equivalent refactor"}
    pool = get_mutant_pool(module_id)
    if not pool:
        return 0.0, {"gate": True, "mutants": 0}
    killed = sum(0 if _run_suite_once(mut, suite_src) else 1 for mut in pool)
    return killed / len(pool), {"gate": True, "killed": killed, "mutants": len(pool)}


_TESTBENCH_TEMPLATE = """You are TestBench-Forge. Write a Python test suite for the function below.

MODULE: {func}
{description}

Reference implementation (correct):
```python
{reference}
```

Write one or more functions named `test_*()` that call `{func}(...)` and `assert` correct
behavior. Your suite is scored by the fraction of HIDDEN, freshly-injected bugs (mutants of
the reference) that it CATCHES (a test fails on the buggy version). So probe edge cases,
boundaries, and adversarial inputs — not just the happy path.

Hard rules:
  - Your suite MUST pass on the correct reference AND on behavior-equivalent refactors. A
    suite that fails the reference (e.g. `assert False`, or tests tied to internal details)
    scores 0.
  - You cannot see the mutants. Maximize coverage of distinct behaviors to kill unseen bugs.

Reference behavior on a few inputs:
{examples}

Reply with ONLY the Python test code (a ```python block is fine)."""


def build_testbench_prompt(module_id: str) -> str:
    m = MODULES[module_id]
    func = m["func"]
    inputs = m["edges"][:5]
    sig = _eval_signature(m["reference"], func, [list(a) for a in inputs])
    ex = "\n".join(f"  {func}{tuple(a)} -> {s[3:] if s.startswith('OK:') else s}"
                   for a, s in zip(inputs, sig))
    return _TESTBENCH_TEMPLATE.format(
        func=func, description=m["description"], reference=m["reference"].strip(), examples=ex)
